services:
  frontend:
    image: frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-networks

  backend:
    image: backend:latest
    networks:
      - app-networks

networks:
  app-networks:
    driver: bridge
